export {default as HomePage} from './HomePage'
export {default as Navbar} from './Navbar'
export {default as Search} from './Search'
export {default as FamousProduct} from './FamousProduct'
export {default as CardProduct} from './CardProduct'
export {default as ProductPage} from './ProductPage'
export {default as Footer} from './Footer'
export {default as RelatedProduct} from './RelatedProduct'